app1/urls.py
from django.urls import path

from . import views

app_name = 'app1'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',views.log_in, name='login'),
    path('logout/',views.log_out, name='logout'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('register/',views.register, name='register'),
    path('dashboard/create',views.create,name='create'),
    path('dashboard/edit/<int:id>',views.edit,name='edit'),
    path('dashboard/delete/<int:id>',views.delete,name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app1.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

app1/models.py
from django.db import models
import datetime


class Users(models.Model):
    username = models.CharField(max_length=20)

    def __str__(self):
        return self.username


class Events(models.Model):
    username = models.ForeignKey(Users, on_delete=models.CASCADE)
    title = models.CharField(max_length =200)
    description = models.TextField()
    location = models.CharField(max_length=200)
    date = models.DateTimeField('date of event')
    attended_or_not = models.CharField(max_length=20,default="NO")

    def __str__(self):
        return self.title

app1/forms.py
from django import forms
import datetime

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class EventForm(forms.Form):
    title = forms.CharField(max_length =200)
    description = forms.CharField(widget=forms.Textarea())
    location = forms.CharField(max_length=200)
    date = forms.DateTimeField(widget=forms.DateTimeInput())
    attended_or_not = forms.CharField(max_length=20)

app1/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404

from django.http import HttpResponse, HttpResponseRedirect

from .models import Users, Events

from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import login, authenticate,logout

from django.contrib.auth.decorators import login_required

from .forms import UserLoginForm, EventForm

from django.contrib.auth.models import User


def home(request):
    if request.user.is_authenticated:
        return redirect('app1:dashboard')
    
    return render(request, 'app1/home.html')

def log_in(request):
    if request.user.is_authenticated:
        return redirect('app1:dashboard')
    
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('app1:dashboard')
            else:
                return render(request,'registration/login.html',{'form' : form,'user' : user})
    else:
        form = UserLoginForm
    context = { 'form' : form }
    return render(request,'registration/login.html', context)


def log_out(request):
    logout(request)
    return redirect('app1:home')



def register(request):
    if request.user.is_authenticated:
        return redirect('app1:dashboard')
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            u = User.objects.get(username=username)
            if u is not None:
                c = Users(username=username)
                c.save()
            return redirect('app1:dashboard')
    else:
        form = UserCreationForm()

    context = { 'form' : form }
    return render(request, 'registration/register.html', context)

@login_required(login_url='/login')
def dashboard(request):
    username = request.user
    userkey= get_object_or_404(Users, username= username)
    context = {'userkey' : userkey }
    return render(request, 'app1/dashboard.html',context)

@login_required(login_url='/login')
def create(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            userkey = request.user
            username = get_object_or_404(Users, username=userkey)
            event = username.events_set.create(title=request.POST['title'],description = request.POST['description'],location = request.POST['location'],date = request.POST['date'],attended_or_not = request.POST['attended_or_not'])
            return redirect('app1:dashboard')
    else:
        form = EventForm()

    context = { 'form' : form }
    return render(request,'app1/create.html', context)

@login_required(login_url='/login')
def edit(request,id):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = get_object_or_404(Events,pk=id)
            event.title = request.POST['title']
            event.description = request.POST['description']
            event.location = request.POST['location']
            event.date = request.POST['date']
            event.attended_or_not = request.POST['attended_or_not']
            event.save()
            return redirect('app1:dashboard')
    else:
        event = get_object_or_404(Events,pk=id)
        data={'title' : event.title,
       'description' : event.description,
       'location' : event.location,
       'date' : event.date,
       'attended_or_not' : event.attended_or_not}
        form = EventForm(data)

    context = { 'form' : form, 'event' : event }
    return render(request,'app1/edit.html', context)

@login_required(login_url='/login')
def delete(request,id):
    event = get_object_or_404(Events,pk=id)
    event.delete()
    return redirect('app1:dashboard')

app1/templates/app1/create.html
{% extends 'app1/layout.html' %}
{% block title %}CREATE{% endblock %}
{% block content %}
<div class="container">
  <h3>CREATE EVENT</h3>
  <br>
  <form id="form1" method="POST" action ="{% url 'app1:create' %}" >
    <div class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <button id="bu1" type="submit">Create</button>
    <strong>(format of date is: "%Y-%m-%d %H:%M:%S")</strong>
    </div>
  </form>
</div>
{% endblock %}

app1/templates/app1/dashboard.html
{% extends 'app1/layout.html' %}
{% block content %}
<div id="maindiv">
{% if user.is_authenticated %}
<h3 align="right"> Logged In: {{ user.username }} </h3>
{% else %}
<h3> You are not logged in </h3>
{% endif %}
<br>
<button id="cbutton" class="btn-primary">CREATE EVENT</button>
<a href = "{% url 'app1:logout' %}" class="btn-primary" style="float:right">LOGOUT</a>
<br><br>
<div class="jumbotron">
<h2>EVENTS</h2>
<div id="div1" class="container">
{% for event in userkey.events_set.all %}
<br>
<ul>
     <li><h2>{{ event.title }}</h2></li>
           <ul>
            <li>{{event.description}}</li> 
            <li>{{event.location}}</li>
            <li>{{event.date}}</li>
            <li>attended : {{event.attended_or_not}}</li>
            <br><br>
            <a href = "{% url 'app1:edit' event.id %}" class="btn-primary">EDIT EVENT</a>
            &nbsp;&nbsp;&nbsp;<a href = "{% url 'app1:delete' event.id %}" class="btn-primary">DELETE EVENT</a>
           </ul></ul>{% endfor %}
           <br><br>
        </div>
    </div>
</div>
{% endblock %}

app1/templates/app1/edit.html
{% extends 'app1/layout.html' %}
{% block title %}CREATE{% endblock %}
{% block content %}
<div class="container">
  <h3>EDIT EVENT</h3>
  <br>
  <form method="POST" action ="{% url 'app1:edit' event.id  %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">EDIT</button>
  </form>
</div>
{% endblock %}

app1/templates/app1/home.html
{% extends 'app1/layout.html' %}
{% block content %}
<div class="container">
    <br>
    <div class="jumbotron">
<a href= "{% url 'app1:login' %}" class="btn-primary">LOGIN</a>
&nbsp;&nbsp;&nbsp;&nbsp;
<a href= "{% url 'app1:register' %}" class="btn-primary">SIGN-UP</a>
</div>
</div>
{% endblock %}

app1/templates/app1/layout.html
<!DOCTYPE html>
<html>
    <head>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script>
            $(document).ready(function(){
                $("#cbutton").click(function(){
                    $("#div1").load("{% url 'app1:create' %}");
                });
            });
            </script>
            <script>
                    $(document).ready(function(){
                        $("#form1").submit(function(){
                            $.ajax({ 
                                type: $(this).attr('method'), // GET or POST
                                url: $(this).attr('action'), // the file to call
                                data: $(this).serialize(), // get the form data
                                success: function() {
                                    $('#head2').hide()
                                    $("#maindiv").load("{% url 'app1:dashboard' %}");
                                    }
                                });
                            return false;
                            });
                        });
            </script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <style>
            .btn-primary {
                background: #4285f4;
                border: 1px solid #1266f1;
                color: #ffffff;
                font-family: 'Open Sans', sans-serif;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: 0.23px;
                padding: 12px 32px;
                text-align: center;
                text-decoration: none;
                text-transform: uppercase;
        </style>
        <title>
        {% block title %}
            {% endblock %}
        </title>
    </head>
    <body>
        <div class="container">
        <h2 id="head2">
        Event Management Web-App
        </h2>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>